/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ws = 1,
  sym_reader_mac = 2,
  sym_comment = 3,
  aux_sym_many_symchars_token1 = 4,
  aux_sym_many_symchars_token2 = 5,
  anon_sym_COLON = 6,
  sym_main = 7,
  sym_value = 8,
  sym_raw_value = 9,
  sym_symbol = 10,
  sym_many_symchars = 11,
  sym_keyword = 12,
  aux_sym_main_repeat1 = 13,
  aux_sym_value_repeat1 = 14,
  aux_sym_value_repeat2 = 15,
  aux_sym_many_symchars_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ws] = "ws",
  [sym_reader_mac] = "reader_mac",
  [sym_comment] = "comment",
  [aux_sym_many_symchars_token1] = "many_symchars_token1",
  [aux_sym_many_symchars_token2] = "many_symchars_token2",
  [anon_sym_COLON] = ":",
  [sym_main] = "main",
  [sym_value] = "value",
  [sym_raw_value] = "raw_value",
  [sym_symbol] = "symbol",
  [sym_many_symchars] = "many_symchars",
  [sym_keyword] = "keyword",
  [aux_sym_main_repeat1] = "main_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_value_repeat2] = "value_repeat2",
  [aux_sym_many_symchars_repeat1] = "many_symchars_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ws] = sym_ws,
  [sym_reader_mac] = sym_reader_mac,
  [sym_comment] = sym_comment,
  [aux_sym_many_symchars_token1] = aux_sym_many_symchars_token1,
  [aux_sym_many_symchars_token2] = aux_sym_many_symchars_token2,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_main] = sym_main,
  [sym_value] = sym_value,
  [sym_raw_value] = sym_raw_value,
  [sym_symbol] = sym_symbol,
  [sym_many_symchars] = sym_many_symchars,
  [sym_keyword] = sym_keyword,
  [aux_sym_main_repeat1] = aux_sym_main_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_value_repeat2] = aux_sym_value_repeat2,
  [aux_sym_many_symchars_repeat1] = aux_sym_many_symchars_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [sym_reader_mac] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_many_symchars_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_many_symchars_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_main] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_many_symchars] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_main_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_many_symchars_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        0, 3,
        '#', 6,
        ',', 5,
        ':', 9,
        '\'', 5,
        ';', 5,
        '|', 5,
        '~', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(7);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_ws);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_ws);
      if ((!eof && lookahead == 00)) ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_reader_mac);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_many_symchars_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_many_symchars_token2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ws] = ACTIONS(1),
    [sym_reader_mac] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_many_symchars_token1] = ACTIONS(1),
    [aux_sym_many_symchars_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_main] = STATE(17),
    [sym_value] = STATE(2),
    [sym_raw_value] = STATE(5),
    [sym_symbol] = STATE(12),
    [sym_many_symchars] = STATE(13),
    [sym_keyword] = STATE(12),
    [aux_sym_main_repeat1] = STATE(2),
    [aux_sym_value_repeat1] = STATE(4),
    [aux_sym_many_symchars_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [aux_sym_many_symchars_token1] = ACTIONS(11),
    [aux_sym_many_symchars_token2] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(5),
    [sym_symbol] = STATE(12),
    [sym_many_symchars] = STATE(13),
    [sym_keyword] = STATE(12),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(4),
    [aux_sym_many_symchars_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [aux_sym_many_symchars_token1] = ACTIONS(11),
    [aux_sym_many_symchars_token2] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(5),
    [sym_symbol] = STATE(12),
    [sym_many_symchars] = STATE(13),
    [sym_keyword] = STATE(12),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(4),
    [aux_sym_many_symchars_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_ws] = ACTIONS(19),
    [sym_reader_mac] = ACTIONS(22),
    [sym_comment] = ACTIONS(25),
    [aux_sym_many_symchars_token1] = ACTIONS(28),
    [aux_sym_many_symchars_token2] = ACTIONS(28),
    [anon_sym_COLON] = ACTIONS(31),
  },
  [STATE(4)] = {
    [sym_raw_value] = STATE(8),
    [sym_symbol] = STATE(12),
    [sym_many_symchars] = STATE(13),
    [sym_keyword] = STATE(12),
    [aux_sym_value_repeat1] = STATE(15),
    [aux_sym_many_symchars_repeat1] = STATE(6),
    [sym_ws] = ACTIONS(34),
    [sym_reader_mac] = ACTIONS(36),
    [sym_comment] = ACTIONS(9),
    [aux_sym_many_symchars_token1] = ACTIONS(11),
    [aux_sym_many_symchars_token2] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_ws,
    STATE(7), 1,
      aux_sym_value_repeat2,
    ACTIONS(43), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [17] = 4,
    STATE(9), 1,
      aux_sym_many_symchars_repeat1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(49), 2,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
    ACTIONS(47), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [34] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym_ws,
    STATE(10), 1,
      aux_sym_value_repeat2,
    ACTIONS(57), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [51] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(57), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [68] = 4,
    STATE(9), 1,
      aux_sym_many_symchars_repeat1,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(66), 2,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
    ACTIONS(64), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [85] = 4,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      sym_ws,
    STATE(10), 1,
      aux_sym_value_repeat2,
    ACTIONS(74), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [102] = 4,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      sym_ws,
    STATE(10), 1,
      aux_sym_value_repeat2,
    ACTIONS(81), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [119] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(85), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [131] = 2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(89), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [143] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(93), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [155] = 4,
    ACTIONS(95), 1,
      sym_ws,
    ACTIONS(98), 1,
      sym_reader_mac,
    STATE(15), 1,
      aux_sym_value_repeat1,
    ACTIONS(101), 4,
      sym_comment,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
      anon_sym_COLON,
  [171] = 3,
    STATE(6), 1,
      aux_sym_many_symchars_repeat1,
    STATE(14), 1,
      sym_many_symchars,
    ACTIONS(103), 2,
      aux_sym_many_symchars_token1,
      aux_sym_many_symchars_token2,
  [182] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 17,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 68,
  [SMALL_STATE(10)] = 85,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 119,
  [SMALL_STATE(13)] = 131,
  [SMALL_STATE(14)] = 143,
  [SMALL_STATE(15)] = 155,
  [SMALL_STATE(16)] = 171,
  [SMALL_STATE(17)] = 182,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_many_symchars, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_many_symchars, 1, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_many_symchars, 1, 0, 0), SHIFT(9),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(10),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_many_symchars_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_many_symchars_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_many_symchars_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0), SHIFT_REPEAT(10),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 3, 0, 0), SHIFT(10),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_janet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "janet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
