/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ws = 1,
  sym_reader_mac = 2,
  aux_sym_symchars_token1 = 3,
  aux_sym_symchars_token2 = 4,
  anon_sym_COLON = 5,
  sym_main = 6,
  sym_value = 7,
  sym_raw_value = 8,
  sym_symchars = 9,
  sym_keyword = 10,
  aux_sym_main_repeat1 = 11,
  aux_sym_value_repeat1 = 12,
  aux_sym_value_repeat2 = 13,
  aux_sym_keyword_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ws] = "ws",
  [sym_reader_mac] = "reader_mac",
  [aux_sym_symchars_token1] = "symchars_token1",
  [aux_sym_symchars_token2] = "symchars_token2",
  [anon_sym_COLON] = ":",
  [sym_main] = "main",
  [sym_value] = "value",
  [sym_raw_value] = "raw_value",
  [sym_symchars] = "symchars",
  [sym_keyword] = "keyword",
  [aux_sym_main_repeat1] = "main_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_value_repeat2] = "value_repeat2",
  [aux_sym_keyword_repeat1] = "keyword_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ws] = sym_ws,
  [sym_reader_mac] = sym_reader_mac,
  [aux_sym_symchars_token1] = aux_sym_symchars_token1,
  [aux_sym_symchars_token2] = aux_sym_symchars_token2,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_main] = sym_main,
  [sym_value] = sym_value,
  [sym_raw_value] = sym_raw_value,
  [sym_symchars] = sym_symchars,
  [sym_keyword] = sym_keyword,
  [aux_sym_main_repeat1] = aux_sym_main_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_value_repeat2] = aux_sym_value_repeat2,
  [aux_sym_keyword_repeat1] = aux_sym_keyword_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [sym_reader_mac] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symchars_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symchars_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_main] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_symchars] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_main_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if ((!eof && lookahead == 00)) ADVANCE(3);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '\'' ||
          lookahead == ';' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(6);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(6);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_ws);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_ws);
      if ((!eof && lookahead == 00)) ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_reader_mac);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_symchars_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_symchars_token2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ws] = ACTIONS(1),
    [sym_reader_mac] = ACTIONS(1),
    [aux_sym_symchars_token1] = ACTIONS(1),
    [aux_sym_symchars_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_main] = STATE(16),
    [sym_value] = STATE(2),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(14),
    [aux_sym_main_repeat1] = STATE(2),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(14),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(14),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_ws] = ACTIONS(15),
    [sym_reader_mac] = ACTIONS(18),
    [anon_sym_COLON] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym_symchars] = STATE(5),
    [aux_sym_keyword_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(24),
    [sym_ws] = ACTIONS(24),
    [sym_reader_mac] = ACTIONS(26),
    [aux_sym_symchars_token1] = ACTIONS(28),
    [aux_sym_symchars_token2] = ACTIONS(28),
    [anon_sym_COLON] = ACTIONS(26),
  },
  [STATE(5)] = {
    [sym_symchars] = STATE(5),
    [aux_sym_keyword_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(30),
    [sym_ws] = ACTIONS(30),
    [sym_reader_mac] = ACTIONS(32),
    [aux_sym_symchars_token1] = ACTIONS(34),
    [aux_sym_symchars_token2] = ACTIONS(34),
    [anon_sym_COLON] = ACTIONS(32),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_COLON,
    ACTIONS(37), 1,
      sym_ws,
    ACTIONS(39), 1,
      sym_reader_mac,
    STATE(10), 1,
      sym_raw_value,
    STATE(14), 1,
      sym_keyword,
    STATE(15), 1,
      aux_sym_value_repeat1,
  [19] = 2,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(43), 4,
      sym_reader_mac,
      aux_sym_symchars_token1,
      aux_sym_symchars_token2,
      anon_sym_COLON,
  [30] = 4,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym_ws,
    STATE(9), 1,
      aux_sym_value_repeat2,
    ACTIONS(50), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [44] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(57), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [58] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_ws,
    STATE(12), 1,
      aux_sym_value_repeat2,
    ACTIONS(57), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [72] = 4,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(67), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [86] = 4,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(74), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [100] = 2,
    ACTIONS(76), 2,
      aux_sym_symchars_token1,
      aux_sym_symchars_token2,
    STATE(4), 2,
      sym_symchars,
      aux_sym_keyword_repeat1,
  [109] = 2,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(80), 2,
      sym_reader_mac,
      anon_sym_COLON,
  [118] = 4,
    ACTIONS(82), 1,
      sym_ws,
    ACTIONS(85), 1,
      sym_reader_mac,
    ACTIONS(88), 1,
      anon_sym_COLON,
    STATE(15), 1,
      aux_sym_value_repeat1,
  [131] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 19,
  [SMALL_STATE(8)] = 30,
  [SMALL_STATE(9)] = 44,
  [SMALL_STATE(10)] = 58,
  [SMALL_STATE(11)] = 72,
  [SMALL_STATE(12)] = 86,
  [SMALL_STATE(13)] = 100,
  [SMALL_STATE(14)] = 109,
  [SMALL_STATE(15)] = 118,
  [SMALL_STATE(16)] = 131,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symchars, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symchars, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(12),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 3, 0, 0), SHIFT(11),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_janet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "janet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
