/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ws = 1,
  sym_reader_mac = 2,
  sym_comment = 3,
  aux_sym_symchars_token1 = 4,
  aux_sym_symchars_token2 = 5,
  anon_sym_COLON = 6,
  sym_main = 7,
  sym_value = 8,
  sym_raw_value = 9,
  sym_symchars = 10,
  sym_keyword = 11,
  aux_sym_main_repeat1 = 12,
  aux_sym_value_repeat1 = 13,
  aux_sym_value_repeat2 = 14,
  aux_sym_keyword_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ws] = "ws",
  [sym_reader_mac] = "reader_mac",
  [sym_comment] = "comment",
  [aux_sym_symchars_token1] = "symchars_token1",
  [aux_sym_symchars_token2] = "symchars_token2",
  [anon_sym_COLON] = ":",
  [sym_main] = "main",
  [sym_value] = "value",
  [sym_raw_value] = "raw_value",
  [sym_symchars] = "symchars",
  [sym_keyword] = "keyword",
  [aux_sym_main_repeat1] = "main_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_value_repeat2] = "value_repeat2",
  [aux_sym_keyword_repeat1] = "keyword_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ws] = sym_ws,
  [sym_reader_mac] = sym_reader_mac,
  [sym_comment] = sym_comment,
  [aux_sym_symchars_token1] = aux_sym_symchars_token1,
  [aux_sym_symchars_token2] = aux_sym_symchars_token2,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_main] = sym_main,
  [sym_value] = sym_value,
  [sym_raw_value] = sym_raw_value,
  [sym_symchars] = sym_symchars,
  [sym_keyword] = sym_keyword,
  [aux_sym_main_repeat1] = aux_sym_main_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_value_repeat2] = aux_sym_value_repeat2,
  [aux_sym_keyword_repeat1] = aux_sym_keyword_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [sym_reader_mac] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symchars_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symchars_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_main] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_symchars] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_main_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        0, 3,
        '#', 6,
        ',', 5,
        ':', 9,
        '\'', 5,
        ';', 5,
        '|', 5,
        '~', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(7);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_ws);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_ws);
      if ((!eof && lookahead == 00)) ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_reader_mac);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_symchars_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_symchars_token2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ws] = ACTIONS(1),
    [sym_reader_mac] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_symchars_token1] = ACTIONS(1),
    [aux_sym_symchars_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_main] = STATE(16),
    [sym_value] = STATE(2),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(13),
    [aux_sym_main_repeat1] = STATE(2),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(13),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_ws] = ACTIONS(5),
    [sym_reader_mac] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_value] = STATE(3),
    [sym_raw_value] = STATE(8),
    [sym_keyword] = STATE(13),
    [aux_sym_main_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_ws] = ACTIONS(17),
    [sym_reader_mac] = ACTIONS(20),
    [sym_comment] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(26),
  },
  [STATE(4)] = {
    [sym_symchars] = STATE(5),
    [aux_sym_keyword_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_ws] = ACTIONS(29),
    [sym_reader_mac] = ACTIONS(31),
    [sym_comment] = ACTIONS(31),
    [aux_sym_symchars_token1] = ACTIONS(33),
    [aux_sym_symchars_token2] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(31),
  },
  [STATE(5)] = {
    [sym_symchars] = STATE(5),
    [aux_sym_keyword_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_ws] = ACTIONS(35),
    [sym_reader_mac] = ACTIONS(37),
    [sym_comment] = ACTIONS(37),
    [aux_sym_symchars_token1] = ACTIONS(39),
    [aux_sym_symchars_token2] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COLON,
    ACTIONS(42), 1,
      sym_ws,
    ACTIONS(44), 1,
      sym_reader_mac,
    STATE(10), 1,
      sym_raw_value,
    STATE(13), 1,
      sym_keyword,
    STATE(14), 1,
      aux_sym_value_repeat1,
  [22] = 2,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(48), 5,
      sym_reader_mac,
      sym_comment,
      aux_sym_symchars_token1,
      aux_sym_symchars_token2,
      anon_sym_COLON,
  [34] = 4,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_ws,
    STATE(9), 1,
      aux_sym_value_repeat2,
    ACTIONS(55), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [49] = 4,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(62), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [64] = 4,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_ws,
    STATE(12), 1,
      aux_sym_value_repeat2,
    ACTIONS(62), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [79] = 4,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(72), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [94] = 4,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      sym_ws,
    STATE(11), 1,
      aux_sym_value_repeat2,
    ACTIONS(79), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [109] = 2,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_ws,
    ACTIONS(83), 3,
      sym_reader_mac,
      sym_comment,
      anon_sym_COLON,
  [119] = 4,
    ACTIONS(85), 1,
      sym_ws,
    ACTIONS(88), 1,
      sym_reader_mac,
    STATE(14), 1,
      aux_sym_value_repeat1,
    ACTIONS(91), 2,
      sym_comment,
      anon_sym_COLON,
  [133] = 2,
    ACTIONS(93), 2,
      aux_sym_symchars_token1,
      aux_sym_symchars_token2,
    STATE(4), 2,
      sym_symchars,
      aux_sym_keyword_repeat1,
  [142] = 1,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 22,
  [SMALL_STATE(8)] = 34,
  [SMALL_STATE(9)] = 49,
  [SMALL_STATE(10)] = 64,
  [SMALL_STATE(11)] = 79,
  [SMALL_STATE(12)] = 94,
  [SMALL_STATE(13)] = 109,
  [SMALL_STATE(14)] = 119,
  [SMALL_STATE(15)] = 133,
  [SMALL_STATE(16)] = 142,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symchars, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symchars, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 3, 0, 0), SHIFT(11),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_janet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "janet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
